### ISSUE TITLE
When running script with 2 access keys set profile.json is cleared

### ISSUE THREAD

**Issue by alepeltier** [AJ-Carterr/aws-account-switcher#1]
I think this might be a niche bug but if I have two access keys set and run the script it throws a "Cannot exceed quota for AccessKeysPerUser: 2" error but then removes the contents of profiles.json. I think it might be a good idea to check for the key quota before running any code. I'm happy to create an MR to solve this issue.

Here is the error:

`An error occurred (LimitExceeded) when calling the CreateAccessKey operation: Cannot exceed quota for AccessKeysPerUser: 2
Traceback (most recent call last):
  File "switcher.py", line 150, in <module>
    rotate_keys()
  File "switcher.py", line 94, in rotate_keys
    new_key = json.loads(bash('aws iam create-access-key --user-name {}'.format(username)))['AccessKey']
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by JoshCarter-ops** [comment]
Yes, that's interesting I've only ever run the code where I have 1 access key. 
Feel free to have a look if you'd like - I'll assign to myself and also have a stab at solving it.

**Comment by JoshCarter-ops** [comment]
https://github.com/AJ-Carterr/aws-account-switcher/tree/bug/key-quota-fix-jc
Has been pushed based on looking at how many keys you have for that account and skipping the auto rotation if you have more than 1 key...this may not be the best solution but will solve your issue.
